networks:
  deploy-guide-dev:
    driver: bridge
services:
  webapp:
    environment:
      - ConnectionString=Server=postgres;Port=5432;Database=postgres;Username=postgres;Password=Ans13042002
    image: webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    ports: [ 8080:8080 ]
    networks:
      - deploy-guide-dev
    depends_on: [ postgres ]
  postgres:
    image: postgres:16
    # set shared memory limit when using docker-compose
    shm_size: 256mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: Ans13042002
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports :
      - "5434:5432" 
    networks:
      - deploy-guide-dev
    volumes: [ "./pg_data:/var/lib/postgresql/data/" ]